### ISSUE TITLE
Binaries strip

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots#119]
Binaries (particularly Webots) are stripped (symbols are removed) in release mode. This has the advantage of reduce the binary size, but has the cons to hide the stacks of the crash reports.

It's simple to drop this, but a preliminary investigation about the binary size increase would be good.

**Comment by fabienrohrer** [comment]
I implemented this proposition in #136.

On macOS, the binary pass from 6'022'116 to 7'115'796 octets.

The crash report in release mode is much more pertinent:

| With strip (master) | Without Strip (this PR) |
|---|---|
| <img width="1112" alt="with strip" src="https://user-images.githubusercontent.com/866788/51682734-69d5be00-1fe8-11e9-9a24-f58335e199f6.png"> |  <img width="1068" alt="without strip" src="https://user-images.githubusercontent.com/866788/51682735-69d5be00-1fe8-11e9-8c45-33d1a957ce75.png"> |

**Comment by DavidMansolino** [comment]
I will test this for Windows tomorrow.

**Comment by fabienrohrer** [comment]
Great, thank you for the help.

**Comment by DavidMansolino** [comment]
On Windows the size difference is a bit bigger but not so bad: 8'168Ko VS 5'034Ko
But I am not getting any crash report.

**Comment by DavidMansolino** [comment]
Here is what I can get from the crash report (without using the dump file previously mentioned):
![capture](https://user-images.githubusercontent.com/2461619/51830473-3a78c700-22f0-11e9-8972-527b34216650.PNG)

**Comment by fabienrohrer** [comment]
On linux, the stack is displayed on stderr in case of crash. The binary pass from 6'793'856 to 7'977'256 octets.

But surprisingly, the same stack (with Webots function names) is visible with or without the `g++ -s` option.

**Comment by fabienrohrer** [comment]
Regarding to the results, it seems to be only useful to remove the strip option on macOS.

**Comment by fabienrohrer** [comment]
Implemented in #136
