### ISSUE TITLE
Sometimes Jenkins fails on the mirror_supervisor rendering test

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots#143]
**Describe the Bug**

Sometimes, Jenkins fails on the `mirror_supervisor` rendering test:

FAILURE with mirror_supervisor: The white color of the mirror image in the 3D scene is wrong.

https://cyberbotics2.cyberbotics.com:8443/job/Webots/223/console

**Comment by DavidMansolino** [comment]
Replaced by #742 (for Travis instead of Jenkins)
