### ISSUE TITLE
Improve linear_motor.wbt Node hierarchy

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots#171]
**Describe the Bug**
The node hierarchy of the linear motor simulation should be improved. It does contain useless group node and empty transform node.

Furthermore with the AMD radeon R5 the ruler is to much transparent.
Nvidia GTX 980:
![linear_motor](https://user-images.githubusercontent.com/2461619/52409891-1890f880-2ad7-11e9-8a1b-94c323fe4665.png)

Radeon R5:
![linear_motor](https://user-images.githubusercontent.com/2461619/52409901-1c247f80-2ad7-11e9-87b2-afa73fb3cd08.png)

**Comment by fabienrohrer** [comment]
The issue with the transparency is related with the `OpenGL/textureQuality` parameter. At low, the object is transparent, at high it is less transparent and more blue. I will investigate why.

**Comment by fabienrohrer** [comment]
The smooth scale operation of Qt image clearly alternates the alpha value (3 times or so):
https://github.com/omichel/webots/blob/master/src/webots/nodes/WbImageTexture.cpp#L138
