### ISSUE TITLE
Robot not moving in pioneer2.wbt

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots#186]
**Describe the Bug**
The robot in pioneer2.wbt is not moving:
* in the R2019a revision 1 world opened with Webots R2018b the robot moves
* in the R2018b world opened with Webots R2019a revision 1 the robot doesn't move

**Steps to Reproduce**
1. Open and start pioneer2.wbt

**System**
 - Operating System: Linux Ubuntu 18.04

**Comment by stefaniapedrazzi** [comment]
Same for khepera.wbt (and probably other robots using braitenber controller).

**Comment by DavidMansolino** [comment]
It seems to be a problem with the kinematic model of the differentialWheels as it seems to work fine with the epuck.
