### ISSUE TITLE
Main 3D View Anti-Aliasing Preference Should be a Checkbox

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots#190]
**Describe the Bug**
The main 3d view anti-aliasing preference should be a checkbox since the only options are 'enabled' or 'disabled'.

**Screenshots**
![capture](https://user-images.githubusercontent.com/2461619/52559137-beed3e80-2df4-11e9-841a-0de179b4a924.PNG)

**Comment by omichel** [comment]
This should be cleaned up when we implement camera post-processing (including GTAO). Also, I believe we should remove the distinction between camera and main view. The new preferences should simply offer to enable shadows, GTAO, SMAA and texture quality. This will affect both the main view and robot cameras.

**Comment by DavidMansolino** [comment]
> This should be cleaned up when we implement camera post-processing (including GTAO).

This is already implemented on develop.

>  believe we should remove the distinction between camera and main view.

:+1:
