### ISSUE TITLE
Telemetry Issue with Bolean Data

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots#206]
**Describe the Bug**
All the bolean data recorded by the telemetry are wrong.

**Steps to Reproduce**
1. Disable the camera anti-aliasing.
2. Open any world.
3. Check your entry in https://cyberbotics.com/telemetry => the  camera anti-aliasing is not marked as disabled

**System**
 - Operating System: Windows 10

**Additional context**
Probably an issue with the default value type provided when retrieving the value, e.g.: https://github.com/omichel/webots/blob/master/src/webots/core/WbTelemetry.cpp#L60

**Comment by DavidMansolino** [comment]
The problem seems to be on the server side, on Webots side we are sending correct data.

**Comment by omichel** [comment]
I just fixed it.

**Comment by DavidMansolino** [comment]
Thank you, I confirm it is now working fine!
