### ISSUE TITLE
Streaming failures on Linux

### ISSUE THREAD

**Issue by omichel** [omichel/webots#211]
**Describe the Bug**
The streaming mode either crashes Webots or hangs.

**Steps to Reproduce**
1. webots --stream projects/samples/devices/worlds/motor.wbt
2. open resources/web/streaming_viewer/index.html and connect

&rarr; the loading of the 3D view in the web browser hangs

1. webots --stream projects/vehicles/automobile/highway.wbt
2. open resources/web/streaming_viewer/index.html and connect

&rarr; Webots crashes

**Screenshots**
![screenshot from 2019-02-13 07-01-46](https://user-images.githubusercontent.com/1264964/52721062-22b86880-2fa9-11e9-841e-1c9565c01044.png)

**Note:** see the strange `textureTransform="` text above the 3D view.

**System**
 - Operating System: Ubuntu 18.04 running in VMware on Windows 10 with hardware acceleration enabled
 - Graphics Card: NVIDIA GeForce GTX970

**Comment by fabienrohrer** [comment]
I cannot reproduce on macOS native. Streams work as expected.

**Comment by omichel** [comment]
It may be due to some OpenGL bug on VMware (again).

**Comment by fabienrohrer** [comment]
I checked and it's not related with textureQuality (my first hypothesis reading this)

**Comment by omichel** [comment]
I just tested on Windows and it works as expected.

**Comment by omichel** [comment]
Can someone test it on a native Linux, to see if it's VMware related?

**Comment by DavidMansolino** [comment]
>Can someone test it on a native Linux, to see if it's VMware related?

I am doing this right now.

**Comment by fabienrohrer** [comment]
On my VM, I have a browser crash (!) on highway.wbt, but 1. motor.wbt works smoothly.

**Comment by DavidMansolino** [comment]
On my native Linux both are working (highway is a bit slow in the web browser while running).

**Comment by omichel** [comment]
Yes, I would assume this highway.wbt is too heavy (texture wise) for a VM graphics to run both Webots and the webGL view, so let's close this issue as I see no simple way to fix it.

**Comment by omichel** [comment]
Thank you for the tests!

**Comment by fabienrohrer** [comment]
Ok that sounds good.
