### ISSUE TITLE
Tinkerbot Project Location is Wrong

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots#224]
**Describe the Bug**
The tinkerbot project does not follow our hierarchy rule (projects/robots/manufacturer/robot_name/)

**Expected behavior**
It should be located in `projects/robots/kinematics/tinkerbots`.

Was this made on purpose to avoid 'kinematics' problematic name ?

**Comment by DavidMansolino** [comment]
Similar issue with `sphero` it should be `sphero/bb8/`

**Comment by fabienrohrer** [comment]
> Was this made on purpose to avoid 'kinematics' problematic name?

No, it's indeed an issue to fix.

**Comment by DavidMansolino** [comment]
Fixed in #457
