### ISSUE TITLE
GlossyCarPaint and MatteCarPaint are too specific

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots#276]
GlossyCarPaint and MatteCarPaint appearances are slightly used in other contexts.
They are basically a flat surface painted with a glossy or matte paint. Or metallized paint?

I propose to simply remove the "Car" keyword from their names.
@all Is it ok like this, or do you have better propositions?

**Comment by omichel** [comment]
It seems to refer to paint on a metallic or bodywork surface, which may be different from a wooden or plastic surface... Why not replacing "Car" with "Bodywork"?

**Comment by DavidMansolino** [comment]
From the definitions I found, `Bodywork` seems to be related to vehicles only, but these appearances should be much more generic.

**Comment by fabienrohrer** [comment]
I think that the matter (if it's flat and without defaults) behind the paint does not affect much the final rendering if the paint cover it perfectly (which is the case here).

**Comment by omichel** [comment]
Ok, then, I am fine to remove the "Car" word as initially proposed by @fabienrohrer.

**Comment by fabienrohrer** [comment]
👍 
Ok, I will go forward like this.

**Comment by fabienrohrer** [comment]
CarLeather suffers from the same issue.

**Comment by omichel** [comment]
Same problem, same solution 😄

**Comment by fabienrohrer** [comment]
Fixed in #277
