### ISSUE TITLE
Wrong sphere texture mapping in WREN

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots#281]
**Describe the Bug**
The texture mapping for a sphere displayed in Webots doesn't match the X3D texture mapping.

**Steps to Reproduce**
1. Go to 'textured_shapes.wbt'
2. Export HTML5 model
3. Open the exported model in a browser
4. The texture mapping in the browser and in Webots for the sphere are different in the top and bottom area

**Expected behavior**
The sphere texture mapping in WREN should match the X3D one.

**Screenshots**
Webots:
![textured_shapes_webots](https://user-images.githubusercontent.com/5910449/54345907-4c19f200-4644-11e9-83c0-d47759e5ba14.png)
x3dom:
![Screenshot from 2019-03-14 10-28-41](https://user-images.githubusercontent.com/5910449/54345800-15dc7280-4644-11e9-85df-e14bf5bf608b.png)
view3dscene:
![textured_shapes_view3dscene](https://user-images.githubusercontent.com/5910449/54345793-0d843780-4644-11e9-927f-a5d24b83fd6d.png)

**Comment by fabienrohrer** [comment]
The fix should probably target R2019b instead, because it may have consequences for the users to fix the Webots mapping. Is this true?

**Comment by stefaniapedrazzi** [comment]
Yes, i will target 2019b.
I don't think that users will have to change anything, but sensors can behave slightly differently.

**Comment by stefaniapedrazzi** [comment]
The mismatch comes from the different triangulation of the sphere:

![sphere_triangulation](https://user-images.githubusercontent.com/5910449/54348520-78843d00-4649-11e9-8729-605aef9531ef.png)

The WREN implementation (icosphere) is probably better as all the triangles are about the same size. But it doesn't match the sphere (uv sphere shape used by X3D (x3dom) and THREE.js.

I checked in Blender and both primitives `UV Sphere` and `Icosphere` are available.
If we want to keep the icosphere, then we have to export it as IndexedFaceSet and not as a Sphere geometry.

**Comment by omichel** [comment]
Yes, let's do this: export our Sphere primitive as mesh for THREE.js.

**Comment by DavidMansolino** [comment]
Linked to #254

**Comment by stefaniapedrazzi** [comment]
During the meeting we discussed to add a flag to the Sphere node specifying if the mapping/triangulation type: icosphere or uv-sphere.

* Webots: by default creates an icosphere
* VRML import: it imports a uv-sphere
* VRML/X3D export:
  * uv spheres are exported as Sphere
  * icospheres are exported as IndexedFaceSet

The flag could be called "uv" or "ico"

**Comment by omichel** [comment]
I have a small preference for "ico".

**Comment by stefaniapedrazzi** [comment]
THREEjs has the `IcosahedronGeometry` that corresponds to the icosphere.
So we could maybe use the Sphere node when exporting to x3d (not VRML) instead of the IndexedFaceSet.

**Comment by stefaniapedrazzi** [comment]
Fixed in #407
