### ISSUE TITLE
HTML PI encoding not interpreted in code block

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots#309]
In https://www.cyberbotics.com/doc/reference/pointlight the PI character is still displayed as `&pi;`.

Probably it is correct that in the code block everything is written as is and it is not interpreted, but in this case it would be better to just show `pi` instead of `&pi;`.

**Comment by omichel** [comment]
I don't understand this value of 4&pi;. Can anyone explain it?

**Comment by DavidMansolino** [comment]
It probably comes from the formula of the sphere surface: A = 4πr^2
