### ISSUE TITLE
How to draw in Webots

### ISSUE THREAD

**Issue by lesun90** [omichel/webots#348]
**Is your feature request related to a problem? Please describe.**
Hi, I am looking for a way to draw in webots, I do some researches about this but none of the solutions meet my need. The "display device" method only draw on a grid, the create shape method is trivial since I need to draw hundreds of items. 

For example, I want to draw something like this on the floor:
![Untitled](https://user-images.githubusercontent.com/2374913/55727516-27fdc680-59e0-11e9-9e81-9a5d8c9c9aa1.jpg)

And this is not possible using the drawing methods in webots right now 

I found that webots was supported to draw using OpenGL before, and it exactly what I need.

**Comment by fabienrohrer** [comment]
We indeed dropped the OpenGL draw ability a while ago.

The recommended way is now to use a Supervisor to modify an existing IndexedLineSet (or another primitive), as shown in this example: https://cyberbotics.com/doc/guide/samples-howto#supervisor_draw_trail-wbt
I think this new way is adapted for your application.

An alternative is to draw this figure in a texture using a Display, and to display this texture on the ground. There is an example here: https://cyberbotics.com/doc/guide/samples-devices#display-wbt
This is certainly simpler to setup.

Finally, you can modify the Webots code to do so. But this is much more difficult to do. A good starting point is around the rendering function: https://github.com/omichel/webots/blob/master/src/webots/gui/WbWrenWindow.cpp#L229
We won't provide you help if you choose this solution.
