### ISSUE TITLE
Too Big Images in Docs

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots#361]
Some of the images in the doc have way too high resolutions and slow down the page loading with slow/medium connections. This is particularly visible in the samples and robots pages.
For example on this page: https://cyberbotics.com/doc/guide/samples-devices
There are a lot of big images which are actually displayed very small.

We should probably keep this big images for the future when we will support modal images, but for the preview we should use smaller images.

**Comment by fabienrohrer** [comment]
My original plan was to create an automatic thumbnail mechanism and the possibility to see the original images in a modal window.

**Comment by DavidMansolino** [comment]
That would be indeed a cleaner mechanism, but I think we should do this urgently (as last week when I was showing to the doc to potential clients it was giving a bad image of the doc to have it loading slowly).
