### ISSUE TITLE
OpenCV example crashes on startup on Windows

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots#376]
"el" on Discord reports us that `vision.wbt` crashes on startup on Windows:

> when i run the vision.wbt world it says this
INFO: vision: Starting: ""D:\Programs\Webots\projects\samples\howto\controllers\vision\vision.exe""
WARNING: vision: The process crashed some time after starting successfully.
WARNING: 'vision' controller crashed.

I looked quickly at this issue, and it seems that OpenCV libraries are [well installed](https://github.com/omichel/webots/blob/master/src/install_scripts/msys64_installer.sh#L28
), but not [well released](https://github.com/omichel/webots/blob/master/src/packaging/files_msys64.txt).
I didn't test more yet.

**Comment by DavidMansolino** [comment]
Fixed in  #389
