### ISSUE TITLE
Windows build: Requested Qt version not available

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots#379]
**Describe the Bug**

When following Windows instructions, the `msys64_installer.sh` script fails on this issue:

```
Qt5 version requested: 5.12.2
Qt5 version installed: 5.10.1-2
Qt5 version available: 5.12.3-1
Requested version not available
```

**Steps to Reproduce**

From a clean Windows install, follow the build instructions of the wiki until executing `msys64_installer.sh`.

- The script seems to do a lot of things, among other related with Qt.
- `./msys64` is not created.
- A user reports the same on Discord ("el").

**Screenshots**

<img width="1680" alt="Capture d’écran 2019-04-23 à 16 14 54" src="https://user-images.githubusercontent.com/866788/56588079-fa6d6b80-65e2-11e9-8cda-0f36c44a6540.png">

**Comment by omichel** [comment]
I believe we should fix it on the `master` branch. I can take care of it.

**Comment by fabienrohrer** [comment]
Ok thank you. Yes, it's clearly an `hotfix` in my point of view too.
