### ISSUE TITLE
Webots cannot start on Windows with current MSYS2

### ISSUE THREAD

**Issue by omichel** [omichel/webots#384]
The workaround is simple: copy libicu*62.dll from an installed Webots R2019a revision 1 to the development environment:

`cp /C/Program\ Files/Webots/msys64/mingw64/bin/libicu*62.dll ~/webots/msys64/mingw64/bin`

The problem was reported here: https://github.com/msys2/MINGW-packages/issues/5273 and should be fixed soon hopefully.

**Comment by fabienrohrer** [comment]
For conveniency, I created an archive with the files to copy:
[libicu.zip](https://github.com/omichel/webots/files/3112115/libicu.zip)

**Comment by omichel** [comment]
Fixed. See https://github.com/msys2/MINGW-packages/issues/5273
