### ISSUE TITLE
Conflicting dependencies on Linux 

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots#423]
On Ubuntu 18.04 when installing the `npm` package required to install babel and create `webots.min.js` the following packages are removed:
* `libssh-dev`
* `libssh-dev`

and these new packages are installed:
* `libssl1.0-dev`
* `node-gyp`
* `nodejs-dev`
* `npm`

as a consequence there are compilation issues with the RobotisOP2 robot window:

```
In file included from TransferWidget.cpp:16:0:
SSH.hpp:25:10: fatal error: libssh/callbacks.h: No such file or directory
 #include <libssh/callbacks.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/stefi/develop/webots/resources/Makefile.include:679: recipe for target 'build/debug/TransferWidget.o' failed
```

We need to fix the compilation and update the installation instructions.

**Comment by stefaniapedrazzi** [comment]
Maybe the compilation issues are fixed by a `make clean`, I'm checking.
But the installation instructions should be improved as it doesn't make sense to install dependencies and remove them later.

**Comment by stefaniapedrazzi** [comment]
No, even after `make clean` I get the same compilation error.

**Comment by stefaniapedrazzi** [comment]
This is a known issue of nodejs v8 (current default version).
Installing nodejs v10 fixes the issue as the dependencies have been fixed.

**Comment by fabienrohrer** [comment]
Well spotted!

**Comment by stefaniapedrazzi** [comment]
I just updated the installation instructions:
https://github.com/omichel/webots/wiki/Linux-Optional-Dependencies
