### ISSUE TITLE
Upgrade the robot components to the new webots.min.js

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots#433]
Porting the robot components to the new THREEjs viewer becomes important.

It's currently broken in some branches:
https://github.com/omichel/webots/pull/430

**Comment by stefaniapedrazzi** [comment]
On develop I'm also getting this error in the terminal when starting Webots:
```
QString::arg: Argument missing: (%s:%u, %s), file:///home/stefi/webots/docs/dependencies/wwi/R2019b/webots.min.js
QString::arg: Argument missing: "(%s:%u, %s)" , 1
QString::arg: Argument missing: (%s:%u, %s), 
Critical: Uncaught ReferenceError: THREE is not defined(%s:%u, %s)
```

Updating the `dependencies.txt` file was not solving the issue, but maybe updating `docs/js/viewer.js` does it. If not I will inspect the issue after #435 is merged.

**Comment by fabienrohrer** [comment]
After updating dependencies.txt as proposed in https://github.com/omichel/webots/pull/435/files, did you run the docs/local_exporter.py script?

**Comment by stefaniapedrazzi** [comment]
probably not.. I will check

**Comment by DavidMansolino** [comment]
Can we close this issue?

@stefaniapedrazzi do you still have the error ?

**Comment by stefaniapedrazzi** [comment]
Running `.local_exporter.py` was not solving the issue.
But I checked again on `develop` and it seems to work.
