### ISSUE TITLE
--minimize option not working on Ubuntu

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots#453]
Launching webots with the `--minimize` option is not working on Ubuntu.

<img width="1680" alt="Capture d’écran 2019-05-15 à 11 39 36" src="https://user-images.githubusercontent.com/866788/57765646-2c677e80-7706-11e9-8043-4888f883e432.png">

**Comment by DavidMansolino** [comment]
I can't reproduce the problem on Ubuntu 16.04 on master.

**Comment by DavidMansolino** [comment]
For me (on Ubuntu 16.04) it is working fine on revision and develop too.

**Comment by stefaniapedrazzi** [comment]
Calling `showNormal()` followed by `setWindowState(Qt::WindowMinimized)` seems to work on my Ubuntu 18.04 and the application is not displayed on the screen.

**Comment by stefaniapedrazzi** [comment]
I could reproduce the same issue based on a Qt example and I reported it:
https://bugreports.qt.io/browse/QTBUG-76354

**Comment by stefaniapedrazzi** [comment]
I just checked and this Qt bug has been fixed in Qt 5.14.2.
The current version used on Linux is 5.13.1. When updating to the latest Qt version we can get rid of the hotfix introduced in  #563.
