### ISSUE TITLE
Upgrade three.js

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots#455]
We are currently using threejs r100.

We should upgrade it to r105:
- The upgrade is required to use the latest post processing effects (several differences between r100 and r105)
- As told [here](https://github.com/omichel/webots/pull/435#issuecomment-492640868), Object3d.clone() is buggy in r100 and cause issues on the Khepera1 import.
- GPUPicker should be upgraded to r105 and maintained by ourself.

I think this should deserve a dedicated PR.

**Comment by DavidMansolino** [comment]
@fabienrohrer can we close this issue?

**Comment by fabienrohrer** [comment]
Yes, thank you!
