### ISSUE TITLE
three.js webots.min.js loading information

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots#471]
The new webots.min.js may take long time to load models. Especially for textures.

Some information about loading time (the lady bug, or a progress bar, or both?) would be welcome.

Could the texture loading be asynchronous as before?

**Comment by stefaniapedrazzi** [comment]
> Could the texture loading be asynchronous as before?

Not sure to understand what do you mean.
The texture loading is already asynchronous in `webots.min.js`.
But probably the `render` function is called only after the scene is fully loaded.

**Comment by fabienrohrer** [comment]
You're right, we are already close to the optimal: the render function is called once after the x3d load, and once after each texture load. The result is a bit weird but it's difficult to do better.

**Comment by fabienrohrer** [comment]
The result after #508 is more comprehensive. The GUI is not blocked during the texture load. I think we can safely close this issue.
