### ISSUE TITLE
tinkerbots_demo vehicle does not detects the cubie anymore

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots#562]
**Steps to Reproduce**

1. Open tinkerbots_demo.wbt
2. Play
3. The vehicle doesn't "distance sensor B" acts weirdly => the vehicle never detects the cubie => the vehicle remains still

**Comment by fabienrohrer** [comment]
It seems to not be due to my recent modifications on the tinkerbots (I can reproduce it on `revision` and not on `master`)

**Comment by DavidMansolino** [comment]
It may be due to #340.

**Comment by fabienrohrer** [comment]
Yes, I just test this, and it's indeed the cause of this issue, thank you.
