### ISSUE TITLE
Rounding issues saving float values to WBT file

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots#582]
There are rounding issues writing float values to world file.
This only occurs for some specific values, for example 1.6 but not 1.5.

**Steps to Reproduce**
1. Open new world
2. Change `Viewpoint.far` to 1.6
3. Save the world
-> in the WBT file the far value is exported as `far 1.5999999999999998`

**Expected behavior**
The export field value should be `far 1.6` and not `far 1.5999999999999998`

**System**
 - Operating System: Linux Ubuntu 18.04

**Comment by stefaniapedrazzi** [comment]
The value is already rounded in Webots before writing it to file.

**Comment by stefaniapedrazzi** [comment]
On my PC the correct value `1.6` is changed to `1.599999999999999` here: https://github.com/omichel/webots/blob/eafc9e5324690b1250696d790df982a788425000/src/webots/maths/WbPrecision.cpp#L74

**Comment by stefaniapedrazzi** [comment]
The problem comes from the fact that when editing from the field editor, the internal field value in Webots is stored with a precision (GUI_MEDIUM) lower than the one used when writing the value to file (DOUBLE_MAX).

Fixing the way the values are rounded in the field editor code also fixes the problem on WBT write:
* store internal value with DOUBLE_MAX precision
* round value to GUI_MEDIUM when displaying it to in the field editor

**Comment by stefaniapedrazzi** [comment]
Actually it doesn't seem to fix the problem: for some values it works but not for others.
The value set by the QDoubleSpinBox often it is not a rounded value: for example `0.29999999999999998890` when typing 0.3.
And sometimes the `WbPrecision::roundValue` function with DOUBLE_MAX precision in some cases increases the distance from the rounded value: for example from `0.29999999999999998890` to `0.30000000000000004441`.

**Comment by omichel** [comment]
This is inherent to the nature of IEEE floating point representation, as explained here: https://0.30000000000000004.com.

**Comment by stefaniapedrazzi** [comment]
Yes. But if we want to set and store rounded values (with a high precision) we cannot loose precision in between.

**Comment by stefaniapedrazzi** [comment]
Removing this rounding:
https://github.com/omichel/webots/blob/eafc9e5324690b1250696d790df982a788425000/src/webots/scene_tree/WbDoubleEditor.cpp#L84
makes the storing work correctly much more often than even increasing the precision to DOUBLE_MAX. But still sometimes it fails.

**Comment by stefaniapedrazzi** [comment]
Maybe I found a working method.

**Comment by DavidMansolino** [comment]
It seems the issue is not fixed. In #656 I have tons of rounding issues.
To reproduce the problem, simply open the battery.wbt world, move one of the block with the arrows and save:
```diff
--- a/projects/samples/devices/worlds/battery.wbt
+++ b/projects/samples/devices/worlds/battery.wbt
@@ -62,7 +62,7 @@ DEF BLUE_BOX Solid {
   }
 }
 DEF YELLOW_BOX Solid {
-  translation -0.2 0.05 0.15
+  translation -0.12631299999999998 0.049999999999999996 0.118848
   rotation 0 1 0 0.4
   children [
     Shape {

```

**Comment by DavidMansolino** [comment]
A probably linked issue is that if you change the `Solid.rotationStep` field, then it is not possible to restore the default value, the default value is restored but still appears as non-default (probably because of the rounding).

**Comment by stefaniapedrazzi** [comment]
Just for note:
- the issue with the default value seems to be introduced in #627 
- issues when moving objects with the handles was already reproducible before #627

**Comment by stefaniapedrazzi** [comment]
Removing the rounding here fixes the problem with the handles:
 https://github.com/omichel/webots/blob/3a446d433e81c5cb293c593316438631a0d6b49e/src/webots/gui/WbDragTransformEvent.cpp#L91

**Comment by stefaniapedrazzi** [comment]
It seems that reverting the rounding introduced in #266 to fix rounding issue solves the problem at least on my system..
