### ISSUE TITLE
Online documentation still referring to R2019a

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots#611]
Not sure if this is a temporary issue until R2019b is released, but in the R2019b documentation page there are references to R2019a

https://www.cyberbotics.com/doc/reference/index?version=R2019b
![Screenshot from 2019-06-19 11-59-27](https://user-images.githubusercontent.com/5910449/59756388-e7e17c80-9289-11e9-9432-c35a9558d7ba.png)

**Comment by stefaniapedrazzi** [comment]
This is the same in the offline documentation

**Comment by fabienrohrer** [comment]
The version has not been updated correctly in showdown-extension.js, I'm taking care of this.

**Comment by fabienrohrer** [comment]
Well spotted, by the way ^^
