### ISSUE TITLE
Mismatch Between Webots and Webots.js

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots#628]
**Describe the Bug**
In the `telemax.wbt` world, if you connect to the streaming server after the led gets on, the rendering is hugely different:

![Capture du 2019-06-20 16-43-58](https://user-images.githubusercontent.com/2461619/59858430-3e7ab380-937b-11e9-86b2-d7b43cc4ff02.png)

**Comment by fabienrohrer** [comment]
More info about this bug: 

On the first connection it's loaded correctly and the result is quite good:

<img width="1680" alt="Capture d’écran 2019-06-24 à 08 44 47" src="https://user-images.githubusercontent.com/866788/59997992-9dcc1280-965e-11e9-98cb-c257cfc3c1c5.png">

When disconnecting/connecting without reloading the page, the environment map is not updated correctly.
This is certainly easy to fix.
