### ISSUE TITLE
Robot fall to pieces during training

### ISSUE THREAD

**Issue by xiaoxianSun** [omichel/webots#635]
**Describe the Bug**
I using Pioneer 3-AT to training a reinforcement algorithm. But during the training process, the robot fall into pieces.   

**Expected behavior**
Is there any operation that i can avoid this problem? Or can I detect this problem through some sensors automaticlly? 

**Screenshots**
![webots_broken](https://user-images.githubusercontent.com/38597172/59990703-ccee7e00-9676-11e9-845e-978864c2a0a3.png)

**System**
 - Operating System: Linux Ubuntu 16.04
 - Graphics Card: [e.g., NVIDIA GeForce RTX 2080 11 GB, AMD Radeon RX 580 8GB, etc.]

**Additional context**

**Comment by xiaoxianSun** [comment]
I am using webots2019a

**Comment by fabienrohrer** [comment]
How do you reset the robot position?

You can for example reset the entire world like this:

```
from controller import Supervisor

supervisor = Supervisor()
timestep = int(supervisor.getBasicTimeStep())

while supervisor.step(timestep) != -1:
    if supervisor.getTime() > 2.0:  # after 2 seconds
        supervisor.worldReload(). # reload the entire world
```

**Comment by xiaoxianSun** [comment]
Thank you for your help! I have try this, but the training speed is slower.I think can combine these two method.
I use the example of projects/languages/python/controllers/driver    translationField.setSFVec3f(self.translation)

**Comment by fabienrohrer** [comment]
You should certainly reset the physics just after the `setSFVec3f` call: https://www.cyberbotics.com/doc/reference/supervisor?tab=python#wb_supervisor_simulation_reset_physics

**Comment by fabienrohrer** [comment]
> I have try this, but the training speed is slower.I think can combine these two method.

Sorry, I meant using the "supervisor RESET" function which is supposed to be very quick in comparison of the supervisor RELOAD because it reset only the solid positions and the controllers: https://cyberbotics.com/doc/reference/supervisor?tab=python#wb_supervisor_simulation_reset

```python
from controller import Supervisor

supervisor = Supervisor()
timestep = int(supervisor.getBasicTimeStep())

while supervisor.step(timestep) != -1:
    if supervisor.getTime() > 2.0:  # after 2 seconds
        supervisor.worldReset()
```

**Comment by xiaoxianSun** [comment]
> 
Thank you ! I will have try this!
> ```

**Comment by xiaoxianSun** [comment]
> > I have try this, but the training speed is slower.I think can combine these two method.
> 
> Sorry, I meant using the "supervisor RESET" function which is supposed to be very quick in comparison of the supervisor RELOAD because it reset only the solid positions and the controllers: https://cyberbotics.com/doc/reference/supervisor?tab=python#wb_supervisor_simulation_reset
> 
> ```python
> from controller import Supervisor
> 
> supervisor = Supervisor()
> timestep = int(supervisor.getBasicTimeStep())
> 
> while supervisor.step(timestep) != -1:
>     if supervisor.getTime() > 2.0:  # after 2 seconds
>         supervisor.worldReset()
> ```

> Thank you! I will have a try!

**Comment by xiaoxianSun** [comment]
> > I have try this, but the training speed is slower.I think can combine these two method.
> 
> Sorry, I meant using the "supervisor RESET" function which is supposed to be very quick in comparison of the supervisor RELOAD because it reset only the solid positions and the controllers: https://cyberbotics.com/doc/reference/supervisor?tab=python#wb_supervisor_simulation_reset
> 
> ```python
> from controller import Supervisor
> 
> supervisor = Supervisor()
> timestep = int(supervisor.getBasicTimeStep())
> 
> while supervisor.step(timestep) != -1:
>     if supervisor.getTime() > 2.0:  # after 2 seconds
>         supervisor.worldReset()
> ```

Thank you ! I will have a try!

**Comment by fabienrohrer** [comment]
Did you solved the issue?

**Comment by fabienrohrer** [comment]
@xiaoxianSun Did you solved the issue this way?

**Comment by fabienrohrer** [comment]
I consider this issue fixed.

@xiaoxianSun Feel free to reopen it if it's not the case 😉
