### ISSUE TITLE
AppVeyor Nighlty Build failure

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots#707]
Travis returned a failure on this nightly build on revision, however no failure is visible in the log output and the nightly release was correctly uploaded:

https://ci.appveyor.com/project/omichel/webots-sj08b?fullLog=true

**Comment by omichel** [comment]
It seems it just hit the timeout (1 hour).
Not sure how to fix it.

**Comment by omichel** [comment]
And it was not uploaded.

**Comment by DavidMansolino** [comment]
You're right indeed that's just a timeout issue, the creation of the package is extremely long, it started at 0:45:00 and hit the timeout :-/
