### ISSUE TITLE
Importing objects is blocking

### ISSUE THREAD

**Issue by schra** [omichel/webots#760]
In order to mitigate the slow importing times (#493), I want to start the simulation and then lazily load parts of the world around my vehicle during the simulation. That's why I ran into the problem that the importing functions (e.g. `wb_supervisor_field_import_mf_node_from_string`) are blocking (blocking the sense of halting the simulation). Is there any way to import objects without halting the simulation and without having a (much) reduced simulation rate?

I already tried to import only one object at a time and then calling `wb_robot_step` each time. But this way the simulation rate is far less than 1, i.e. importing each object already has a huge delay associated with it.

I also tried to import the object inside a thread while the main thread calls `wb_robot_step` but it seems that you don't support multithreading?

```
#include <array>
#include <chrono>
#include <iostream>
#include <string>
#include <thread>
#include <webots/robot.h>
#include <webots/supervisor.h>

WbNodeRef root_node;
WbFieldRef root_children_field;

int const insert_position = 0;
int const num_objects_to_measure = 1000;

// btw here is also some kind of race: sometimes Webots will just stop creating
// Solids at a random number of Solids

void import_n_objects_individually(int n, char const *object) {
  for (; n >= 0; --n) {
    wb_supervisor_field_import_mf_node_from_string(root_children_field,
                                                   insert_position, object);
  }
}

int main() {
  wb_robot_init();

  root_node = wb_supervisor_node_get_root();
  root_children_field = wb_supervisor_node_get_field(root_node, "children");

  std::thread import_nodes([=]() {
    import_n_objects_individually(num_objects_to_measure, "Solid { }");
  });

  while (true) {
    wb_robot_step(1);
    puts("step");
  }

  wb_robot_cleanup();
  return 0;
}
```

**Comment by omichel** [comment]
Although the libController is supporting multi-threading, multi-threading is clearly not the solution to this problem. Unfortunately, I see no good solution this way.
