### ISSUE TITLE
Python shebang line should override the python command from the Webots preferences

### ISSUE THREAD

**Issue by omichel** [omichel/webots#798]
Webots should parse the shebang line of python controllers if any, e.g., `#!/usr/bin/env python` to determine which version of python to use. If not shebang line is specified, Webots should use the python command specified in the `runtime.ini`. If not specified, it should finally revert to the python command set in the Webots preferences.

**Comment by DavidMansolino** [comment]
Can we close this issue (#800)?

**Comment by omichel** [comment]
Yes!
